version: "3.8"

services:
    web:
        build: .
        ports:
            - 5000:5000
        environment:
            - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_flask
            - POSTGRES_PASSWORD=hello_flask
            - POSTGRES_DB=hello_flask_dev

volumes:
    postgres_data: